# Generated by Django 2.2.10 on 2020-02-27 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDebit', models.BooleanField(default=False)),
                ('acctTypeSelect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acct.AcctType')),
                ('fixedAcct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acct.Acct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['isDebit', 'fixedAcct', 'acctTypeSelect'],
            },
        ),
    ]
