# Generated by Django 2.2.10 on 2020-02-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0002_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='name',
            field=models.CharField(default='', max_length=63),
            preserve_default=False,
        ),
    ]
