# Generated by Django 2.2.10 on 2020-02-28 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acct', '0004_auto_20200227_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderBal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('acct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acct.Acct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
