# Generated by Django 2.2.10 on 2020-03-03 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0005_headerbal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acct',
            options={'ordering': ['user', 'name']},
        ),
        migrations.AlterModelOptions(
            name='headerbal',
            options={'ordering': ['user', 'order']},
        ),
        migrations.AlterModelOptions(
            name='preset',
            options={'ordering': ['user', 'isDebit', 'fixedAcct', 'acctTypeSelect']},
        ),
        migrations.AlterModelOptions(
            name='txn',
            options={'ordering': ['user', '-id']},
        ),
    ]
