# Generated by Django 3.1.2 on 2020-10-31 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0007_monthlyrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyrecord',
            options={'ordering': ['month']},
        ),
    ]
